<?php
function onecommunity_enqueue_customizer_style() {
?>
<style type="text/css" media="all">

:root {
  --dd-main-color: #ff9801;
  --dd-main-border-color: #efefef;
  --dd-background-1: #f4f4f4;
  --dd-background-2: #efefef;
  --dd-color-1: #d1d1d1;
}

.buddypress .main-navs.bp-navs ul li, #object-nav ul li { background:<?php echo get_theme_mod( 'onecommunity_unselected_tabs_bg', '#d1d1d1' ); ?>; }
.top-bar-notifications-container span, .shortcode-bp-groups-tabs-container #object-nav .tabs-nav li.current, .shortcode_go, .shortcode_notice, .shortcode_quotebyauthor, .shortcode-login #shortcode-login-submit, .box-blog-entry .box-blog-cat a, #buddypress .bp-navs ul li.selected, #buddypress .bp-navs ul li.current, .page-numbers.current, .header-top-signin, .user-top-menu-container ul li span, .single-event-image span, .single-event-cat, .offers-container .offer.best, .offers-container a.button, .single-post-category, #object-nav ul li.current, .top-bar-messages span, .woocommerce h2.woocommerce-loop-category__title mark.count, ul.products li.product .woocommerce-listing-item-cat, body.single-product button.single_add_to_cart_button, .woocommerce div.product .woocommerce-tabs ul.tabs li.active, .woocommerce a.checkout-button, #place_order, .buddypress-wrap #group-create-body .bp-cover-image-status p.warning, .buddypress-wrap .bp-feedback.info .bp-icon, .buddypress-wrap .bp-feedback.help .bp-icon, .hero-button.join, #wp-calendar tbody td#today a, #buddypress .main-navs.bp-navs .object-nav-menu li.current, body.dark-mode .page-numbers.current, ul.learnpress-featured li.course-entry .box-course-cat, ul.learn-press-courses li.lp_course .box-course-cat, .learnpress-page .lp-button, ul.learn-press-nav-tabs .course-nav.active::after, ul.learn-press-nav-tabs .course-nav:hover::after, .course-curriculum ul.curriculum-sections .section-content .course-item.item-preview .course-item-status, .widget_lp-widget-popular-courses .widget-body .course-entry .course-detail .course-detail-top .category, .lp-widget .lp-course-info-fields .lp-course-info .lp-label, .lp-label.label-enrolled, .lp-label.label-started, #sidebar .course-category a { background:<?php echo get_theme_mod( 'onecommunity_main_color', '#ff9801' ); ?>!important; }
.load-more-groups span, .leftpullquote, .rightpullquote, .buddypress-wrap .activity-list .load-more a, .buddypress-wrap .activity-list .load-newest a, .header-top-signin, #load-more-posts-classic, #load-more-posts-1, #load-more-courses, .woocommerce .woocommerce-info, .load-more { border-color:<?php echo get_theme_mod( 'onecommunity_main_color', '#ff9801' ); ?>; }
.shortcode_go:hover, .shortcode-login #shortcode-login-submit:hover { background:<?php echo get_theme_mod( 'onecommunity_main_color_hover', '#d37d00' ); ?>!important; }
#buddypress .bp-subnavs ul.subnav li.current { background: <?php echo get_theme_mod( 'onecommunity_subnav_bg_selected', '#cdcdcd' ); ?>!important; }
.woocommerce .woocommerce-info::before { color:<?php echo get_theme_mod( 'onecommunity_main_color', '#ff9801' ); ?>!important; }

#wp-submit, .submit #signup_submit, .wpcf7-submit, #post-topic-reply #submit, #new-topic-post #submit, .my-account #submit, #new-topic-button, .page-template-search-page-php #search-submit, #comment-submit, #send_reply_button, #profile-group-edit-submit, #bbp_reply_submit, #bbp_topic_submit, #send, #submit { color:<?php echo get_theme_mod( 'onecommunity_button_color', '#ffffff' ); ?>!important; background: <?php echo get_theme_mod( 'onecommunity_button_bg', '#ff9801' ); ?>!important; }

body, .nunito-font { font-family: '<?php echo get_theme_mod( 'onecommunity_font_name', 'Nunito' ); ?>'; }

.single-headers #cover::after { background: <?php echo get_theme_mod( 'onecommunity_cover_bg', 'linear-gradient(0deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.6) 11%, rgba(0,0,0,0) 100%)' ); ?>; }

<?php $onecommunity_font_2_enable = get_theme_mod( 'onecommunity_font_2_enable', false );
if ( $onecommunity_font_2_enable == true ) { ?>
#content article p, .subtitle, .comment-content p, .shordcode-recent-comment .recent-comment-content, .activity-inner p, footer .footer-copyright, .groups-list-desc p, .item .update, .bp-left-sidebar-details-item, .bbp-forum-content, .bbp-reply-content p { font-family: '<?php echo get_theme_mod( 'onecommunity_font_name_2', '' ); ?>!important'; }
<?php } ?>

<?php if ( get_theme_mod( 'onecommunity_dark_mode_enable', true ) == true ) { ?>

/*********** Dark mode ***********/
body.dark-mode { color:<?php echo get_theme_mod( 'onecommunity_dark_mode_font_color', '#f0f0f0' ); ?>; background-color: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; border-color:<?php echo get_theme_mod( 'onecommunity_dark_mode_borders_color', '#282627' ); ?>!important; }
body.dark-mode header#main, body.dark-mode footer, body.dark-mode #sidenav, body.dark-mode #loader-wrapper { background-color: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; }

/*********** Borders color ***********/
body.dark-mode #sidenav, body.dark-mode .header-top, body.dark-mode footer, body.dark-mode .sidebar .sidebar-box .sidebar-title, body.dark-mode .sidebar .sidebar-box ul li, body.dark-mode .breadcrumbs, 
body.dark-mode .woocommerce .woocommerce-breadcrumb, body.dark-mode #page-header .breadcrumbs, body.dark-mode select, body.dark-mode fieldset, body.dark-mode pre, body.dark-mode abbr, body.dark-mode acronym, body.dark-mode table, 
body.dark-mode table th, body.dark-mode table td,body.dark-mode input[type="text"], body.dark-mode input[type="date"], body.dark-mode input[type="time"], 
body.dark-mode input[type="datetime-local"], body.dark-mode input[type="week"], body.dark-mode input[type="month"], 
body.dark-mode input[type="email"], body.dark-mode input[type="url"], body.dark-mode input[type="password"], body.dark-mode input[type="search"], body.dark-mode input[type="tel"], body.dark-mode input[type="number"], 
body.dark-mode textarea#comment, body.dark-mode input[type="date"]:focus, body.dark-mode input[type="time"]:focus, 
body.dark-mode input[type="datetime-local"]:focus, body.dark-mode input[type="week"]:focus, body.dark-mode input[type="month"]:focus, 
body.dark-mode input[type="text"]:focus, body.dark-mode input[type="email"]:focus, body.dark-mode input[type="url"]:focus, 
body.dark-mode input[type="password"]:focus, body.dark-mode input[type="search"]:focus, body.dark-mode input[type="tel"]:focus, body.dark-mode input[type="number"]:focus,
body.dark-mode #page-user-login, body.dark-mode #page-user-pass, body.dark-mode .post-navigation div + div, body.dark-mode .image-navigation, body.dark-mode .comment-navigation,
body.dark-mode #header-menu-container .header-menu .nav-ul-container ul, body.dark-mode #header-menu-container .header-menu li li, body.dark-mode #header-menu-container .header-menu > li.current-menu-item, 
body.dark-mode #mobile-nav div.header-menu-mobile-container ul.header-menu-mobile, body.dark-mode #mobile-nav .header-menu-mobile-container ul li, body.dark-mode .subtitle.desc,
body.dark-mode .tagcloud a, body.dark-mode .header-top-login, body.dark-mode .user-top-menu-container ul, body.dark-mode .user-top-menu-container ul li, body.dark-mode .top-bar-messages-container, 
body.dark-mode .top-bar-messages-menu, body.dark-mode .top-bar-messages-menu ul li, body.dark-mode .notifications-list, body.dark-mode .notifications-list li, body.dark-mode .header-search, body.dark-mode .header-search #ajaxsearchpro1_1, body.dark-mode .header-search #ajaxsearchpro1_1 .probox, body.dark-mode .sidebar-box .search-form, 
body.dark-mode #header-search-mobile, body.dark-mode .frontpage-row, body.dark-mode .frontpage-row-3, body.dark-mode .frontpage-row-3-title, body.dark-mode .frontpage-row-4, body.dark-mode .small-leaderboard, 
body.dark-mode .frontpage-row-5, body.dark-mode .frontpage-row-5-left, body.dark-mode .frontpage-row-5 .left, body.dark-mode .offers-container .offer, body.dark-mode .frontpage-row-7.centered-heading, body.dark-mode .single-post-details, body.dark-mode article, 
body.dark-mode .entry-summary, body.dark-mode main#content .thumbnail, body.dark-mode .blog-classic, body.dark-mode .blog-classic .blog-post, body.dark-mode .blog-classic .blog-post .featured-image img, 
body.dark-mode .blog-classic a.more-link, body.dark-mode .box-blog-entry .box-blog-details, body.dark-mode .box-blog-entry.no-thumbnail .box-blog-details, body.dark-mode .single-post main#content aside#left, body.dark-mode .blog-post aside#left, 
body.dark-mode .single-event aside#left, body.dark-mode .related-posts ul li.related-post-entry, body.dark-mode #left .author-bio img.avatar, body.dark-mode .page-links a, body.dark-mode .comments-area h2, 
body.dark-mode .comment-list article, body.dark-mode .comment-list .pingback, body.dark-mode .comment-list .trackback, body.dark-mode .comment-avatar img, body.dark-mode .comment-body, body.dark-mode .comment-content .reply, 
body.dark-mode .no-comments, body.dark-mode .footer-copyright, body.dark-mode .widecolumn .mu_register .mu_alert, body.dark-mode .term-description, body.dark-mode .woocommerce-product-gallery__image img, 
body.dark-mode .woocommerce-product-gallery__image img.wp-post-image, body.dark-mode.woocommerce div.product .woocommerce-tabs ul.tabs li, 
body.dark-mode.woocommerce .woocommerce-tabs ul.tabs.wc-tabs li.woo-object-nav-menu-button .woo-object-nav-menu, body.dark-mode.woocommerce .woocommerce-tabs ul.tabs.wc-tabs li.woo-object-nav-menu-button .woo-object-nav-menu li, 
body.dark-mode .woocommerce table.shop_attributes, body.dark-mode .woocommerce table.shop_attributes th, body.dark-mode .woocommerce table.shop_attributes td, body.dark-mode .woocommerce #tab-reviews #reviews ol.commentlist, 
body.dark-mode .woocommerce #tab-reviews #reviews ol.commentlist li, body.dark-mode .woocommerce #tab-reviews #reviews .review .comment_container img, 
body.dark-mode .woocommerce .sidebar ul.product_list_widget li img.attachment-woocommerce_thumbnail, body.dark-mode .woocommerce table.shop_table, body.dark-mode .woocommerce table.shop_table td, 
body.dark-mode .woocommerce table.shop_table tbody th, body.dark-mode.woocommerce table.shop_table tfoot td, body.dark-mode.woocommerce table.shop_table tfoot th, body.dark-mode .woocommerce table.shop_table .cart-subtotal, 
body.dark-mode .woocommerce table.shop_table .cart-subtotal th, body.dark-mode .woocommerce table.shop_table .cart-subtotal td, body.dark-mode .wpcf7-textarea, 
body.dark-mode .em-events-list > li, body.dark-mode .events-table thead tr th, body.dark-mode .events-table tbody tr td, body.dark-mode .wp_ulike_likers_wrapper .tiles, 
body.dark-mode body.achievement-single-page .gamipress-achievement-earners-list li a img, body.dark-mode .general-box-title, 
body.dark-mode .shortcode-general-list .shortcode-general-list-item, body.dark-mode #shortcode-user-login, body.dark-mode #shortcode-user-pass, body.dark-mode .shortcode-login-bottom, 
body.dark-mode .shortcode-bp-groups-tabs-container .group-box-bottom, body.dark-mode .shortcode-small-recent-posts-container .recent-post-thumb img, body.dark-mode .shortcode-popular-posts .shortcode-popular-posts-menu-drop-down, 
body.dark-mode .shortcode-popular-posts .tab-news-content li, body.dark-mode .shortcode-popular-posts ul li .pop-left img, body.dark-mode #sidenav ul#sidenav-ul, body.dark-mode #sidenav .sidenav-tabs, 
body.dark-mode #sidenav .best-user, body.dark-mode div#dark-mode-container, body.dark-mode #tabs-activity, body.dark-mode #tabs-activity .tabs-activity-nav, 
body.dark-mode #tabs-activity.shortcode-activity .shortcode-activity-list ul.tab-content-list li, body.dark-mode .shortcode-activity .activity-avatar img.avatar, 
body.dark-mode .shortcode-activity .shortcode-activity-list .rtmedia-item-thumbnail img, body.dark-mode .shortcode-events-row, body.dark-mode #shortcode-category-posts .shortcode-category-posts-menu, 
body.dark-mode #shortcode-category-posts .cat-posts-list.col-2 li, body.dark-mode #shortcode-category-posts .cat-posts-list .recent-post-thumb img, body.dark-mode ul.products li.product .woocommerce-listing-item-content, 
body.dark-mode .leaderboard, body.dark-mode .big-leaderboard-row, body.dark-mode .small-leaderboard-row, body.dark-mode .small-leaderboard-row .leaderboard-user img.avatar,
body.dark-mode #buddypress .main-navs.bp-navs .object-nav-menu, body.dark-mode .activity-list.bp-list li.activity-item:first-child, body.dark-mode .activity-update-form #whats-new-avatar, 
body.dark-mode .activity-update-form #whats-new-textarea textarea, body.dark-mode #item-body .activity-update-form, body.dark-mode .activity-update-form #whats-new-post-in-box #whats-new-post-in-box-items .bp-activity-object.selected, 
body.dark-mode .activity-list .activity-item div.item-avatar img, body.dark-mode .activity-list .activity-item .activity-meta.action, body.dark-mode .buddypress-wrap .activity-comments ul, 
body.dark-mode .buddypress-wrap .activity-comments .child-mark, body.dark-mode .buddypress-wrap .activity-list .activity-comments .comment-item .activity-meta.action, body.dark-mode form.ac-form .ac-reply-avatar img, 
body.dark-mode form.ac-form .ac-reply-content .ac-textarea textarea, body.dark-mode .buddypress-wrap .groups-list li .item-block, body.dark-mode .buddypress-wrap .blogs-list li .item-block, body.dark-mode .buddypress-wrap #members-list li .item-avatar, 
body.dark-mode .register-page .signup-form .password-entry, body.dark-mode .register-page .signup-form .password-entry-confirm, body.dark-mode #register-page button.visibility-toggle-link.text-button, 
body.dark-mode #group-create-body .left-menu img.avatar, body.dark-mode .single-headers:not(.has-bp-cover) #item-header-avatar a img, body.dark-mode .sidebar h2.rtm-gallery-title, 
body.dark-mode .sidebar .left-sidebar-details-friends li img, body.dark-mode .single-item.group-members .item-body .filters:not(.no-subnav), 
body.dark-mode .groups-manage-members-list ul li, body.dark-mode .buddypress-wrap .profile.edit .editfield, body.dark-mode .buddypress-wrap .standard-form .wp-editor-container, body.dark-mode #message-threads, 
body.dark-mode #message-threads li, body.dark-mode #message-threads li .thread-from img.avatar, body.dark-mode #message-threads li .thread-to img.avatar, body.dark-mode .bp-messages-content #thread-preview, 
body.dark-mode .bp-messages-content #bp-message-thread-list li, body.dark-mode .bp-messages-content #bp-message-thread-list .message-metadata .avatar, body.dark-mode .bp-messages-content .thread-participants img, 
body.dark-mode .bp-messages-content #thread-preview h2:first-child, body.dark-mode .bp-messages-content #bp-message-thread-header h2:first-child, body.dark-mode .user-messages-bulk-actions .bulk-actions.select-wrap, 
body.dark-mode .message-box .message-metadata .avatar-box img, body.dark-mode .buddypress-wrap .filter select, body.dark-mode .buddypress-wrap #whats-new-post-in-box select, body.dark-mode .buddypress-wrap textarea, 
body.dark-mode .buddypress-wrap .select-wrap, body.dark-mode .buddypress-wrap form.bp-dir-search-form, body.dark-mode .buddypress-wrap form.bp-messages-search-form, body.dark-mode .buddypress-wrap form.bp-invites-search-form,
body.dark-mode .buddypress-wrap .bp-tables-user thead tr, body.dark-mode .buddypress-wrap table.wp-profile-fields thead tr, body.dark-mode .buddypress-wrap table.forum thead tr, 
body.dark-mode .buddypress-wrap .bp-tables-user tr td.label, body.dark-mode .buddypress-wrap table.wp-profile-fields tr td.label, body.dark-mode .buddypress-wrap table.forum tr td.label, 
body.dark-mode .buddypress .buddypress-wrap button, body.dark-mode .buddypress .buddypress-wrap a.button, body.dark-mode .buddypress .buddypress-wrap input[type="submit"], 
body.dark-mode .buddypress .buddypress-wrap input[type="button"], body.dark-mode .buddypress .buddypress-wrap input[type="reset"], body.dark-mode .buddypress .buddypress-wrap ul.button-nav:not(.button-tabs) li a,
body.dark-mode .buddypress .buddypress-wrap .generic-button a, body.dark-mode .buddypress .buddypress-wrap .comment-reply-link, body.dark-mode .buddypress .buddypress-wrap a.bp-title-button, 
body.dark-mode .buddypress .buddypress-wrap .activity-read-more a, body.dark-mode .buddypress .buddypress-wrap input[type="submit"].pending, body.dark-mode .buddypress .buddypress-wrap input[type="button"].pending, 
body.dark-mode .buddypress .buddypress-wrap input[type="reset"].pending, body.dark-mode .buddypress .buddypress-wrap input[type="button"].disabled, body.dark-mode .buddypress .buddypress-wrap input[type="reset"].disabled, 
body.dark-mode .buddypress .buddypress-wrap input[type="submit"][disabled="disabled"], body.dark-mode .buddypress .buddypress-wrap button.pending, body.dark-mode .buddypress .buddypress-wrap button.disabled, 
body.dark-mode .buddypress .buddypress-wrap div.pending a, body.dark-mode .buddypress .buddypress-wrap a.disabled, body.dark-mode .buddypress .buddypress-wrap .text-links-list a.button, 
body.dark-mode .buddypress .buddypress-wrap .bp-list.grid .action a, body.dark-mode .buddypress .buddypress-wrap .bp-list.grid .action button, body.dark-mode .buddypress-wrap #pass-strength-result, 
body.dark-mode .buddypress-wrap .members-list.grid .bp-ajax-message, body.dark-mode .buddypress.widget .item-options, body.dark-mode .buddypress.widget ul.item-list li .item-avatar img, body.dark-mode #rt_media_comment_submit, 
body.dark-mode .sidebar #rtMedia-galary-next, body.dark-mode .sidebar .rtmedia-container ul.rtmedia-list li.rtmedia-list-item div.rtmedia-item-thumbnail img, 
body.dark-mode #item-body ul.rtm-gallery-list li .rtmedia-item-thumbnail img, body.dark-mode table.doctable thead th, body.dark-mode table.doctable tbody td, body.dark-mode .vertical.ajaxsearchpro,
body.dark-mode .vertical.ajaxsearchpro .resdrg .item, body.dark-mode .single-headers:not(.has-bp-cover) .generic-button button, body.dark-mode .single-headers:not(.has-bp-cover) .generic-button a,
body.dark-mode #bbpress-forums .bbp-forums, body.dark-mode #bbpress-forums li.bbp-body ul.forum, body.dark-mode #bbpress-forums li.bbp-body ul.topic, body.dark-mode div.bbp-forum-header,body.dark-mode div.bbp-topic-header,body.dark-mode div.bbp-reply-header,
body.dark-mode #bbpress-forums div.bbp-topic-content code,body.dark-mode #bbpress-forums div.bbp-reply-content code,body.dark-mode #bbpress-forums div.bbp-topic-content pre,body.dark-mode #bbpress-forums div.bbp-reply-content pre,
body.dark-mode .bbp-row-actions #favorite-toggle a, body.dark-mode .bbp-row-actions #favorite-toggle span.is-favorite a, body.dark-mode .bbp-row-actions #subscription-toggle a, body.dark-mode .bbp-row-actions #subscription-toggle span.is-subscribed a
body.dark-mode .bbp-pagination-links a, body.dark-mode .bbp-pagination-links span.current, body.dark-mode .bbp-pagination-links span.current, body.dark-mode #bbpress-forums fieldset.bbp-form,
body.topic-edit.dark-mode .bbp-topic-form div.avatar img,body.reply-edit.dark-mode .bbp-reply-form div.avatar img,body.single-forum.dark-mode .bbp-topic-form div.avatar img,body.single-reply.dark-mode .bbp-reply-form div.avatar img,
body.page.dark-mode .bbp-reply-form code,body.page.dark-mode .bbp-topic-form code,body.single-topic.dark-mode .bbp-reply-form code,body.single-forum.dark-mode .bbp-topic-form code,body.topic-edit.dark-mode .bbp-topic-form code,body.reply-edit.dark-mode .bbp-reply-form code,
body.dark-mode #bbpress-forums #bbp-your-profile fieldset input,body.dark-mode #bbpress-forums #bbp-your-profile fieldset textarea, body.dark-mode #bbpress-forums #bbp-your-profile fieldset span.description,
body.dark-mode #bbpress-forums .bbp-topic-content ul.bbp-topic-revision-log,body.dark-mode #bbpress-forums .bbp-reply-content ul.bbp-topic-revision-log,body.dark-mode #bbpress-forums .bbp-reply-content ul.bbp-reply-revision-log,
body.dark-mode #bbpress-forums p.bbp-topic-meta img.avatar,body.dark-mode #bbpress-forums ul.bbp-reply-revision-log img.avatar,body.dark-mode #bbpress-forums ul.bbp-topic-revision-log img.avatar,body.dark-mode #bbpress-forums div.bbp-template-notice img.avatar,body.dark-mode #bbpress-forums .widget_display_topics img.avatar,body.dark-mode #bbpress-forums .widget_display_replies img.avatar,
body.dark-mode .activity-list li.bbp_topic_create .activity-content .activity-inner, body.dark-mode .activity-list li.bbp_reply_create .activity-content .activity-inner, body.dark-mode .bbp-author-avatar img, body.dark-mode .bbp-replies .hentry,
body.dark-mode #bbpress-forums h1.bbp-big-topic-title, body.dark-mode #bbpress-forums h2.bbp-heading-title,
body.dark-mode .woocommerce-breadcrumb, body.dark-mode .product_list_widget img, body.dark-mode .commentlist, body.dark-mode .commentlist li, body.dark-mode.woocommerce #tab-reviews #reviews .review .comment_container img,
body.dark-mode .profile-fields td, body.dark-mode .preview-pane-header, body.dark-mode .single-message-thread-header, body.dark-mode .gamipress-achievement-earners-list li img, body.dark-mode #drag-drop-area,
body.dark-mode ul.avatar-nav-items, body.dark-mode ul.avatar-nav-items li.body.dark-mode .buddydrive-item, body.dark-mode .buddydrive-item, body.dark-mode .buddydrive-toolbar, body.dark-mode .rtm-user-avatar a img,
body.dark-mode .rtmedia-comment, body.dark-mode #bp-data-export button, body.dark-mode .vc_sep_line, body.dark-mode .wpb_text_column, body.dark-mode .vc_column-inner, body.dark-mode .top-bar-notifications-container, body.dark-mode .header-top-right,
body.dark-mode .elementor-divider-separator, body.dark-mode .elementor-widget-container, body.dark-mode #pagebuilder-container .elementor .elementor-element .elementor-element-populated, body.dark-mode header#main #header-search-mobile .header-search-mobile-field,
body.dark-mode ul.learnpress-featured li.course-entry.no-thumbnail .box-course-details, body.dark-mode ul.learnpress-featured li.course-entry .box-course-details, body.dark-mode ul.learn-press-courses li.lp_course .box-course-details, body.dark-mode .widget-body .course-entry, body.dark-mode .widget-body .course-entry .course-cover img,
body.dark-mode .lp-single-details ul li, body.dark-mode ul.learn-press-nav-tabs, body.dark-mode .course-curriculum ul.curriculum-sections .section-header, body.dark-mode .course-curriculum ul.curriculum-sections .section-content .course-item, body.dark-mode.single-post main#content aside#left, body.dark-mode .blog-post aside#left, body.dark-mode.single-event aside#left,
body.dark-mode .widget_bp_core_recently_active_widget .avatar-block .item-avatar img, body.dark-mode .widget_bp_core_whos_online_widget .avatar-block .item-avatar img, body.dark-mode .sidebar .bp-latest-activities .activity-list footer img.avatar, body.dark-mode .sidebar .bp-user-groups li img, body.dark-mode .sidebar .bp-user-friends li img, body.dark-mode .sidebar .admins-moderators .mods-title, body.dark-mode .sidebar .admins-moderators .mods-title, body.dark-mode .shortcode-small-recent-posts .thumbnail img, body.dark-mode #left-sidebar.bp-group, body.dark-mode #left-sidebar, body.dark-mode .sidebar .sidebar-box .sidebar-title, body.dark-mode .columns-container .spacer-1, body.dark-mode .columns-container .spacer-2, body.dark-mode .frontpage-row-3-col-posts .col h4, body.dark-mode .shortcode-general-list li, body.dark-mode #bp-group-blog .shortcode-small-recent-posts, body.dark-mode #bp-user-blog .shortcode-small-recent-posts, body.dark-mode article.event-location ul:not(#event-location-details) li:first-child, body.dark-mode .category-events ul li:first-child, body.dark-mode article.event-location ul li, body.dark-mode .category-events ul li, body.dark-mode #em-wrapper ul.em-locations-list > li, body.dark-mode .generic-button button, body.dark-mode .generic-button a, body.dark-mode .wp-editor-container, body.dark-mode .sidebar-box .em.em-list-widget .em-item, body.dark-mode .sidebar-box .em-locations-widget .em-item-image img, body.dark-mode #friend-list li.item-entry .item-avatar, .bp-group-activity-preview .bp-group-avatar-content:not(.has-cover-image) img, body.dark-mode .bp-member-activity-preview .bp-member-avatar-content:not(.has-cover-image) img { border-color:<?php echo get_theme_mod( 'onecommunity_dark_mode_borders_color', '#282627' ); ?>!important; }

body.dark-mode .frontpage-3-row-1 .elementor-widget-container { border-color:rgba(256, 256, 256, 0.4)!important; }

/********************************* Borders color (darker) *********************************/
body.dark-mode .generic-button { border-color:<?php echo get_theme_mod( 'onecommunity_dark_mode_borders_color_darker', '#151415' ); ?>!important; }
body.dark-mode #cover .generic-button { border-color: #ffffff!important; }

/********************************* Background colors *********************************/
body.dark-mode #header-menu-container .header-menu .nav-ul-container ul, body.dark-mode #mobile-nav div.header-menu-mobile-container ul.header-menu-mobile, 
body.dark-mode .user-top-menu-container ul, body.dark-mode .top-bar-messages-menu, body.dark-mode .notifications-list, body.dark-mode .header-search .search-form, body.dark-mode .header-search .asp_main_container, body.dark-mode .sidebar-box .search-form, 
body.dark-mode .header-search input[type="search"].search-field, body.dark-mode .sidebar-box input[type="search"].search-field, body.dark-mode .header-search .search-submit, body.dark-mode .sidebar-box .search-submit, 
body.dark-mode .box-blog-entry, body.dark-mode .woocommerce .woocommerce-tabs ul.tabs.wc-tabs li.woo-object-nav-menu-button .woo-object-nav-menu li, 
body.dark-mode .woocommerce .woocommerce-tabs ul.tabs.wc-tabs li.woo-object-nav-menu-button .woo-object-nav-menu, body.dark-mode .woocommerce #tab-reviews #reviews .review .comment_container img,
body.dark-mode .shortcode-login, body.dark-mode .vertical.ajaxsearchpro .mCSBap_draggerRail, body.dark-mode .buddypress-wrap .activity-comments .child-mark,
body.dark-mode .shortcode-popular-posts .shortcode-popular-posts-menu-drop-down, body.dark-mode #sidenav ul#sidenav-ul { background: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; }
body.dark-mode #header-menu-container .header-menu li li, body.dark-mode .tabs-activity-nav, body.dark-mode .profile-fields td, body.dark-mode .editfield select, body.dark-mode .bp-tables-user td, body.dark-mode #groups-list-options,
body.dark-mode .buddydrive-item, body.dark-mode table.doctable tr, body.dark-mode .rtmedia-container, body.dark-mode .rtmedia-single-meta, body.dark-mode input#rt_media_comment_submit { background-color: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; }

body.dark-mode #buddypress .main-navs.main-navs.bp-navs ul li, body.dark-mode #buddypress .main-navs.groups-nav.main-navs.bp-navs ul li, body.dark-mode.woocommerce div.product .woocommerce-tabs ul.tabs li { border-color:<?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; }

@media screen and (max-width:1024px) {
body.dark-mode #left-sidebar { background-color: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg', '#1e1a1b' ); ?>!important; }
}

/********************************* Backgrounds colors (lighter) *********************************/
body.dark-mode .tagcloud a:hover, body.dark-mode .tagcloud a:focus, body.dark-mode form.ac-form .ac-reply-content .ac-textarea textarea:focus, body.dark-mode .buddypress-wrap .standard-form input[required]:focus, 
body.dark-mode .buddypress-wrap .standard-form textarea[required]:focus, body.dark-mode .buddypress-wrap .standard-form select[required]:focus, body.dark-mode #buddypress .wp-editor-container button:hover, 
body.dark-mode .buddypress .buddypress-wrap button:hover, body.dark-mode .buddypress .buddypress-wrap button:focus, .buddypress .buddypress-wrap a.button:focus, body.dark-mode .buddypress .buddypress-wrap a.button:hover, 
body.dark-mode .buddypress .buddypress-wrap input[type="submit"]:focus, body.dark-mode .buddypress .buddypress-wrap input[type="submit"]:hover, .buddypress .buddypress-wrap input[type="button"]:focus, 
.buddypress .buddypress-wrap input[type="button"]:hover, .buddypress .buddypress-wrap input[type="reset"]:focus, body.dark-mode .buddypress .buddypress-wrap input[type="reset"]:hover, 
body.dark-mode .buddypress .buddypress-wrap .button-nav li a:focus, body.dark-mode .buddypress .buddypress-wrap .button-nav li a:hover, body.dark-mode .buddypress .buddypress-wrap .button-nav li.current a, body.dark-mode .buddypress .buddypress-wrap .generic-button,
body.dark-mode .buddypress .buddypress-wrap .generic-button a:focus, body.dark-mode .buddypress .buddypress-wrap .generic-button a:hover, body.dark-mode .buddypress .buddypress-wrap .comment-reply-link:focus, 
body.dark-mode .buddypress .buddypress-wrap .comment-reply-link:hover, .buddypress .buddypress-wrap .activity-read-more a:focus, body.dark-mode .buddypress .buddypress-wrap .activity-read-more a:hover, 
body.dark-mode .buddypress .buddypress-wrap input[type="submit"]:hover.pending, body.dark-mode .buddypress .buddypress-wrap input[type="button"]:hover.pending, body.dark-mode .buddypress .buddypress-wrap input[type="reset"]:hover.pending, body.dark-mode .buddypress .buddypress-wrap input[type="submit"]:hover.disabled, body.dark-mode .buddypress .buddypress-wrap input[type="button"]:hover.disabled, body.dark-mode .buddypress .buddypress-wrap input[type="reset"]:hover.disabled, body.dark-mode .buddypress .buddypress-wrap button.pending:hover, body.dark-mode .buddypress .buddypress-wrap button.disabled:hover, body.dark-mode .buddypress .buddypress-wrap div.pending a:hover, body.dark-mode .buddypress .buddypress-wrap a.disabled:hover {}
body.dark-mode .sidebar-spacer, body.dark-mode hr, body.dark-mode .shortcode-events h2, body.dark-mode .frontpage-row-2::after, body.dark-mode .wrapper .frontpage-row-4::after,
body.dark-mode #tabs-activity.shortcode-activity.col-2 .shortcode-activity-list::before, body.dark-mode #shortcode-category-posts .cat-posts-list::after, body.dark-mode .offers-container .offer.best .label,
body.dark-mode .vertical.ajaxsearchpro, body.dark-mode .vertical.ajaxsearchpro .resdrg .item, body.dark-mode .vertical.ajaxsearchpro .asp_spacer, body.dark-mode #object-nav .tabs-nav li:not(.current), body.dark-mode #object-nav ul li:not(.current),
body.dark-mode #buddypress .main-navs.bp-navs ul li:not(.selected), body.dark-mode .main-navs.users-nav, body.dark-mode .main-navs.groups-nav, body.dark-mode .main-navs, body.dark-mode .directory.activity .main-navs.dir-navs,
body.dark-mode #subnav ul li, body.dark-mode .sidebar .bp-profile-fields .item.bg, body.dark-mode .generic-button, body.dark-mode .buddypress-wrap .bp-feedback, body.dark-mode .register-section select,
body.dark-mode .select-wrap, body.dark-mode #members-list-options, body.dark-mode .shortcode_quote, body.dark-mode .rightpullquote, body.dark-mode .leftpullquote,
body.dark-mode #bbpress-forums li.bbp-header, body.dark-mode .bbp-topic-reply-count span, body.dark-mode #bbpress-forums div.bbp-topic-content code, body.dark-mode #bbpress-forums div.bbp-reply-content code, body.dark-mode #bbpress-forums div.bbp-topic-content pre, body.dark-mode #bbpress-forums div.bbp-reply-content pre,
body.dark-mode #bbpress-forums div.bbp-topic-tags a, body.dark-mode .bbp-pagination .bbp-pagination-links a:hover, body.dark-mode .bbp-pagination-links span.current, body.topic-edit.dark-mode .bbp-topic-form div.avatar img,body.reply-editbody.dark-mode .bbp-reply-form div.avatar img,body.single-forum.dark-mode .bbp-topic-form div.avatar img,body.single-reply.dark-mode .bbp-reply-form div.avatar img,
body.page.dark-mode .bbp-reply-form code,body.page.dark-mode .bbp-topic-form code,body.single-topic.dark-mode .bbp-reply-form code,body.single-forum.dark-mode .bbp-topic-form code,body.topic-edit.dark-mode .bbp-topic-form code,body.reply-edit.dark-mode .bbp-reply-form code,
body.dark-mode #bbpress-forums #bbp-your-profile fieldset span.description, body.dark-mode div.bbp-template-notice,div.indicator-hint, body.dark-mode div.bbp-template-notice.info, body.dark-mode #bbpress-forums #bbp-single-user-details #bbp-user-navigation li.current a,
body.dark-mode .bbp-forum-link, body.dark-mode .bbp-forum-topic-count, body.dark-mode .bbp-forum-reply-count, body.dark-mode .woocommerce-ordering select.orderby, body.dark-mode ul.wc-tabs, body.dark-mode div.product .woocommerce-tabs ul.tabs li,
body.dark-mode .gamipress-achievement-unlock-with-points-button, body.dark-mode select option, body.dark-mode #profile-edit-form .editfield, body.dark-mode .buddydrive-toolbar, body.dark-mode .statusnotice, body.dark-mode .currently-viewing,
body.dark-mode .rtmedia-no-comments, body.dark-mode .rtmedia-comment, body.dark-mode .shortcode_quoteby, body.dark-mode .shortcode_highlight, body.dark-mode .animated-shapes-container,
body.dark-mode .learn-press-progress .progress-bg, body.dark-mode .lp-label, body.dark-mode #sidebar-spacer, body.dark-mode #sidebar-spacer-left, body.dark-mode ul.em-categories-list li, body.dark-mode ul.em-tags-list li { background:<?php echo get_theme_mod( 'onecommunity_dark_mode_bg_lighter', '#282627' ); ?>!important; }

/********************************* Backgrounds colors (darker) *********************************/
body.dark-mode #subnav ul.subnav li.current, body.dark-mode .buddypress-wrap .item-body .subnav-filters .feed a,
body.dark-mode #item-header:not(.has-bp-cover) .generic-button button, body.dark-mode .generic-button a, body.dark-mode .generic-button a, body.dark-mode #members-list .generic-button button,
body.dark-mode .bbp-row-actions #favorite-toggle a, body.dark-mode .bbp-row-actions #favorite-toggle span.is-favorite a, body.dark-mode .bbp-row-actions #subscription-toggle a,body.dark-mode .bbp-row-actions #subscription-toggle span.is-subscribed a,
body.dark-mode .big-leaderboard-row .leaderboard-points, body.dark-mode .bp-pagination a.page-numbers:hover, body.dark-mode #buddydrive-filter, body.dark-mode #bp-create-doc-button, body.dark-mode .bp-xprofile-visibility, body.dark-mode #bp-data-export button, body.dark-mode .shortcode_highlight, body.dark-mode #sidenav ul#sidenav-ul span.group, body.dark-mode .generic-button button { background: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg_darker', '#110f0f' ); ?>!important; }

body.dark-mode #cover .generic-button, body.dark-mode #cover .generic-button a { background:none!important; }


/* Forms background */
body.dark-mode input[type="text"], body.dark-mode input[type="date"], body.dark-mode input[type="time"], body.dark-mode input[type="datetime-local"], body.dark-mode input[type="week"], 
body.dark-mode input[type="month"], body.dark-mode input[type="email"], body.dark-mode input[type="url"], body.dark-mode input[type="password"], body.dark-mode input[type="search"], 
body.dark-mode input[type="tel"], body.dark-mode input[type="number"], body.dark-mode textarea#comment, body.dark-mode #page-user-login, body.dark-mode #page-user-pass, body.dark-mode .post-navigation .post-title, 
body.dark-mode .page-numbers, body.dark-mode #member-dir-pag-bottom .page-numbers, body.dark-mode .pagination-links .page-numbers, body.dark-mode .site .skip-link,
body.dark-mode .offers-container .offer h5, body.dark-mode .offers-container .offer:not(.best) .price, body.dark-mode #page-header, body.dark-mode .single-blog-post-tags a, body.dark-mode .page-links a, 
body.dark-mode .comment-counter, body.dark-mode .woocommerce div.product .woocommerce-tabs ul.tabs, body.dark-mode .woocommerce table.shop_attributes tr:nth-child(even) td, 
body.dark-mode .woocommerce table.shop_attributes tr:nth-child(even) td, body.dark-mode .wpcf7-textarea, body.dark-mode #shortcode-user-login, body.dark-mode #shortcode-user-pass, body.dark-mode #whats-new,
body.dark-mode .bbp-topic-form, body.dark-mode .bbp-reply-form, body.dark-mode .bbp-topic-tag-form, body.dark-mode #bbpress-forums #bbp-your-profile fieldset input, body.dark-mode #bbpress-forums #bbp-your-profile fieldset textarea, body.dark-mode #comment_content { background: <?php echo get_theme_mod( 'onecommunity_dark_mode_bg_forms', '#212121' ); ?>!important; }

/** Text color **/
body.dark-mode, body.dark-mode h1, body.dark-mode h2, body.dark-mode h3, body.dark-mode h4, body.dark-mode h5, body.dark-mode h6, body.dark-mode input[type="text"], body.dark-mode input[type="date"], body.dark-mode input[type="time"], body.dark-mode input[type="datetime-local"], body.dark-mode input[type="week"], body.dark-mode input[type="month"], body.dark-mode input[type="email"], body.dark-mode input[type="url"], body.dark-mode input[type="password"], body.dark-mode input[type="search"], body.dark-mode input[type="tel"], body.dark-mode input[type="number"], body.dark-mode textarea#comment,
body.dark-mode .post-password-form label, body.dark-mode #object-nav ul li, body.dark-mode #object-nav ul li.current a, body.dark-mode #object-nav ul li.selected a, body.dark-mode .dropdown-toggle, body.dark-mode .post-navigation .post-title a, body.dark-mode .post-navigation a:hover .post-title, body.dark-mode .post-navigation a:focus .post-title, body.dark-mode .image-navigation, body.dark-mode .comment-navigation,
div.pagination, body.dark-mode div.pagination .pag-count, body.dark-mode .bbp-pagination .bbp-pagination-count, body.dark-mode .page-numbers, body.dark-mode #member-dir-pag-bottom .page-numbers, body.dark-mode .pagination-links .page-numbers, body.dark-mode #header-menu-container .header-menu a, body.dark-mode #header-menu-container .header-menu li ul li a, body.dark-mode #header-menu-container .header-menu li.current-menu-item ul li a,
body.dark-mode #mobile-nav .header-menu-mobile-container ul a, body.dark-mode .breadcrumbs, body.dark-mode .woocommerce .woocommerce-breadcrumb, body.dark-mode .breadcrumbs a, body.dark-mode .woocommerce  .woocommerce-breadcrumb a, body.dark-mode .sidebar .sidebar-box .sidebar-title,body.dark-mode .sidebar h2.rtm-gallery-title,
body.dark-mode .sidebar .general-box-title, body.dark-mode .widget_calendar tbody a, body.dark-mode .header-top-login, body.dark-mode header#main .top-bar-username, body.dark-mode header#main .top-bar-username a, body.dark-mode .user-top-menu-container ul, body.dark-mode .top-bar-messages-menu, body.dark-mode .top-bar-messages-menu ul li .message-title, body.dark-mode .top-bar-messages-menu ul li.unread .message-title, body.dark-mode .top-bar-messages-menu ul li.view-all,
body.dark-mode .notifications-list, body.dark-mode .notifications-list li a, body.dark-mode .notifications-list li.view-all a, body.dark-mode .sidebar-box input[type="search"].search-field, body.dark-mode .frontpage-style-1 a.hero-button.alternative, 
body.dark-mode .single-post-details .single-blog-comments, body.dark-mode article p, body.dark-mode .entry-title a, body.dark-mode body:not(.search-results) .entry-summary, body.dark-mode .blog-post .subtitle, body.dark-mode main#content aside#left h6, body.dark-mode .page-links a, body.dark-mode .comment-content-time,
body.dark-mode .comment-content-time, body.dark-mode .comment-content-time a, body.dark-mode .comment-metadata, body.dark-mode .pingback .edit-link, body.dark-mode .comment-metadata a, body.dark-mode .pingback .comment-edit-link,
body.dark-mode .comment-reply-title #cancel-comment-reply-link, body.dark-mode .comment-reply-link, body.dark-mode .comment-reply-link:hover, body.dark-mode .comment-reply-link:focus, body.dark-mode .comment-notes, body.dark-mode .comment-awaiting-moderation, body.dark-mode .logged-in-as, body.dark-mode .form-allowed-tags,
body.dark-mode .comment-reply-title small a:hover, body.dark-mode .comment-reply-title small a:focus, body.dark-mode .sidebar, body.dark-mode .sidebar a, body.dark-mode .sidebar select, body.dark-mode .rssSummary, body.dark-mode #wp-calendar, body.dark-mode footer, body.dark-mode .woocommerce-Price-amount,
body.dark-mode .woocommerce-product-details__short-description, body.dark-mode .woocommerce .woocommerce-tabs ul.tabs.wc-tabs li.woo-object-nav-menu-button .woo-object-nav-menu li a, body.dark-mode .events-table,
body.dark-mode .comment-content .count-box, body.dark-mode .bbp-reply-content .count-box, body.dark-mode .comment-text .count-box, body.dark-mode .shortcode-activity .count-box, body.dark-mode .single-post-details .wpulike .count-box,
body.dark-mode .buddypress-wrap .bp-subnavs ul.subnav li a, body.dark-mode .buddypress-wrap .item-body .subnav-filters .feed a, body.dark-mode #buddypress .main-navs.bp-navs .object-nav-menu li a,
body.dark-mode #buddypress .main-navs.bp-navs .object-nav-menu li a span, body.dark-mode #buddypress .main-navs.bp-navs .object-nav-menu li.current a, body.dark-mode #buddypress .main-navs.bp-navs li.object-nav-menu-button .object-nav-menu li a,
body.dark-mode .activity-update-form #whats-new-textarea textarea, body.dark-mode .activity-list .activity-item .activity-header, body.dark-mode .activity-list .activity-item .activity-header a, body.dark-mode .buddypress-wrap .activity-list .load-more a, body.dark-mode .buddypress-wrap .activity-list .load-newest a,
body.dark-mode .buddypress-wrap .activity-comments .acomment-meta, body.dark-mode .buddypress-wrap .activity-comments .acomment-content p, body.dark-mode form.ac-form .ac-reply-content .ac-textarea textarea, body.dark-mode .buddypress-wrap .groups-list h2.groups-title a, body.dark-mode .buddypress-wrap .blogs-list h2.blogs-title a,
body.dark-mode .single-headers h2 a, body.dark-mode .bp-messages-content #bp-message-thread-list .activity,
body.dark-mode .buddypress .buddypress-wrap button, body.dark-mode .buddypress .buddypress-wrap a.button, body.dark-mode .buddypress .buddypress-wrap input[type="submit"], body.dark-mode .buddypress .buddypress-wrap input[type="button"], body.dark-mode .buddypress .buddypress-wrap input[type="reset"], body.dark-mode .buddypress .buddypress-wrap ul.button-nav:not(.button-tabs) li a, body.dark-mode .buddypress .buddypress-wrap .generic-button a, body.dark-mode .buddypress .buddypress-wrap .comment-reply-link, body.dark-mode .buddypress .buddypress-wrap a.bp-title-button, body.dark-mode .buddypress .buddypress-wrap .activity-read-more a,
body.dark-mode .widget.buddypress .item-options a.selected, body.dark-mode #rt_media_comment_submit, body.dark-mode .rtmedia-item-title, body.dark-mode #buddypress div#item-header div#item-header-content h2 a, body.dark-mode .doc-meta,
body.dark-mode .general-box-title, body.dark-mode .recent-comment-content, body.dark-mode .shortcode-bp-groups-tabs-container h6.group-box-title a,
body.dark-mode .shortcode-bp-groups-container .group-box-title, body.dark-mode #groups-list .group-box-title,
body.dark-mode .shortcode-popular-posts .shortcode-popular-posts-menu-drop-down span.current, body.dark-mode #sidenav ul#sidenav-ul li.current, body.dark-mode #tabs-activity .tabs-activity-nav li.current,
body.dark-mode .shortcode-activity ul.tab-content-list li .activity-inner, body.dark-mode .shortcode-activity ul.tab-content-list li .activity-inner p, body.dark-mode .shortcode-activity .count-box, body.dark-mode .shortcode-activity .comments-count,
body.dark-mode #shortcode-category-posts .shortcode-category-posts-menu li.current a, body.dark-mode ul.products li.product .woocommerce-listing-item-content .price, body.dark-mode ul.products li.product .woocommerce-listing-item-content .price ins .amount,
body.dark-mode .big-leaderboard-row a.name, body.dark-mode .big-leaderboard-row .leaderboard-points, body.dark-mode .small-leaderboard-row .leaderboard-position, body.dark-mode .vertical.ajaxsearchpro .resdrg .item h3 a,
body.dark-mode .activity-list .activity-item .activity-inner .rtmedia-activity-text, body.dark-mode .activity-list .activity-item .activity-inner p, body.dark-mode .nav-links a .post-title, body.dark-mode .generic-button button,
body.dark-mode .generic-button a,
body.dark-mode .bbp-topic-reply-count span, body.dark-mode .bbp-breadcrumb-current, body.dark-mode #bbpress-forums div.bbp-topic-tags a, body.dark-mode #bbpress-forums .bbp-forum-info .bbp-forum-content,
body.dark-mode div.bbp-template-notice, body.dark-mode div.indicator-hint, body.dark-mode div.bbp-template-notice a, body.dark-mode #bbpress-forums h1.bbp-big-topic-title, body.dark-mode .bbp-forum-right, body.dark-mode .offers-container .offer.best .label,
body.dark-mode .subsubsub li, body.dark-mode .statusnotice p, body.dark-mode #bp-create-doc-button, body.dark-mode .rtmedia-comment-content,
body.dark-mode .lp-single-details ul li, body.dark-mode blockquote cite::before, body.dark-mode blockquote small::before, body.dark-mode .sidebar .bp-latest-activities .activity-list blockquote p, body.dark-mode .shortcode-recent-comments .content, body.dark-mode .sidebar-box .em.em-list-widget .em-item .em-item-info .em-item-name a { color: <?php echo get_theme_mod( 'onecommunity_dark_mode_font_color', '#dfdfdf' ); ?>!important; }

body.dark-mode .dark-bg h1, body.dark-mode .dark-bg h2, body.dark-mode .dark-bg h3, body.dark-mode .dark-bg h4, body.dark-mode .dark-bg h5, body.dark-mode .dark-bg h6 { color:#ffffff!important; }

/** Darker text color **/
body.dark-mode a, body.dark-mode .post-navigation a, body.dark-mode .related-posts ul li.related-post-entry a, body.dark-mode .single-blog-post-tags a { color: #c2c2c2; }
body.dark-mode .dark-bg a { color:#ffffff; }
body.dark-mode .post-navigation .meta-nav, body.dark-mode #header-menu-container .header-menu li.current-menu-item span, body.dark-mode .breadcrumbs .current, body.dark-mode .widget_recent_entries .post-date, 
body.dark-mode .widget_rss .rss-date, body.dark-mode .widget_rss cite, body.dark-mode .sidebar-box .textwidget p, body.dark-mode .top-bar-messages-menu ul li .message-content-details,
body.dark-mode .top-bar-messages-menu ul li .message-content-details a, body.dark-mode .top-bar-messages-menu ul li .message-content p, body.dark-mode .top-bar-messages-menu ul li.unread .message-content p, body.dark-mode .header-search input[type="search"].search-field,
body.dark-mode .header-search input[type="search"].search-field::placeholder, body.dark-mode .sidebar-box input[type="search"].search-field::placeholder, body.dark-mode p.row-subtitle, body.dark-mode main#content .thumbnail span, body.dark-mode .blog-classic .featured-image span, body.dark-mode #left .author-bio-content,
body.dark-mode .taxonomy-description, body.dark-mode .entry-caption, body.dark-mode .comment-counter, body.dark-mode .wp-caption .wp-caption-text, body.dark-mode body.single-product .woocommerce-review-link, body.dark-mode body.single-product .product_meta,
body.dark-mode .woocommerce #tab-reviews #reviews .star-rating, body.dark-mode .woocommerce .comment-text p.meta, body.dark-mode .woocommerce .comment-text p.meta a, body.dark-mode .woocommerce .comment-text p.meta strong, body.dark-mode .woocommerce .sidebar ul.product_list_widget li .amount,
body.dark-mode .woocommerce .sidebar ul.product_list_widget li ins .amount, body.dark-mode .woocommerce .sidebar ul.product_list_widget li ins, body.dark-mode body.buddypress article.page > .entry-header .entry-title,
body.dark-mode .buddypress-wrap .bp-pagination, body.dark-mode .bp-list li .meta, body.dark-mode .bp-list li .item-meta, body.dark-mode .activity-update-form #whats-new-textarea textarea::placeholder, body.dark-mode .activity-update-form #whats-new-submit #aw-whats-new-reset:hover,
body.dark-mode .activity-list .activity-item .activity-inreplyto, body.dark-mode .activity-list .activity-item .activity-header .activity-time-since, body.dark-mode .activity-permalink .activity-list .activity-item .activity-header .time-since,
body.dark-mode .activity-list .activity-item .activity-content .activity-header, body.dark-mode .activity-list .activity-item .activity-content .comment-header, body.dark-mode .activity-list .activity-item .activity-inner .rtmedia-activity-text,
body.dark-mode .activity-list .activity-item .activity-meta.action .button span, body.dark-mode .buddypress-wrap .activity-comments .acomment-options a, body.dark-mode .buddypress-wrap .activity-comments .activity-meta.action .acomment-reply, body.dark-mode .buddypress-wrap .activity-comments .activity-meta.action .acomment-delete,
body.dark-mode .buddypress-wrap #members-list li .user-update, body.dark-mode .single-headers .group-status, body.dark-mode .single-headers:not(.has-bp-cover) #item-header-details, body.dark-mode .single-headers:not(.has-bp-cover) #item-header-details .user-nicename, body.dark-mode .single-headers:not(.has-bp-cover) #item-header-details .activity, body.dark-mode .single-headers:not(.has-bp-cover) #item-header-details .profile-balance,
body.dark-mode .single-headers #item-header-details .profile-balance .gamipress-user-points-amount, body.dark-mode .single-headers #item-header-details .profile-balance .gamipress-user-points-label,
body.dark-mode .single-headers #item-header-details div, body.dark-mode .sidebar .bp-sidebar-details .no-results p, body.dark-mode .groups-manage-members-list ul .members-manage-buttons a.button,
body.dark-mode .buddypress .bp-invites-content .item-list .item-meta span, body.dark-mode .buddypress .bp-invites-content .group-inviters li, body.dark-mode .buddypress .bp-invites-content li .status,
body.dark-mode .buddypress-wrap .field-visibility-settings, body.dark-mode .buddypress-wrap .field-visibility-settings-header, body.dark-mode .bp-messages-content time, body.dark-mode #message-threads li .thread-from .num-recipients, body.dark-mode #message-threads li .thread-to .num-recipients,
body.dark-mode #message-threads li .thread-content .excerpt, body.dark-mode .bp-messages-content #bp-message-thread-list .message-metadata time, body.dark-mode .bp-messages-content #thread-preview h2.preview-thread-title small,
body.dark-mode .bp-messages-content .thread-participants dt, body.dark-mode .buddypress-wrap .standard-form input:focus, body.dark-mode .buddypress-wrap .standard-form textarea:focus, body.dark-mode .buddypress-wrap .standard-form select:focus,
body.dark-mode .buddypress-wrap .standard-form p.description, body.dark-mode .buddypress-wrap .standard-form div.checkbox label:nth-child(n+2), body.dark-mode .buddypress-wrap .standard-form div.radio div label, body.dark-mode .buddypress-wrap .select-wrap select,
body.dark-mode .buddypress-wrap .select-wrap:focus .select-arrow:before, body.dark-mode .buddypress-wrap .select-wrap:hover .select-arrow:before, body.dark-mode .buddypress-wrap form.bp-dir-search-form input[type="search"]::placeholder,
body.dark-mode .buddypress-wrap table#message-threads .thread-info p.thread-excerpt, body.dark-mode .buddypress .buddypress-wrap input[type="submit"].pending, body.dark-mode .buddypress .buddypress-wrap input[type="button"].pending, body.dark-mode .buddypress .buddypress-wrap input[type="reset"].pending, body.dark-mode .buddypress .buddypress-wrap input[type="button"].disabled, body.dark-mode .buddypress .buddypress-wrap input[type="reset"].disabled, body.dark-mode .buddypress .buddypress-wrap input[type="submit"][disabled="disabled"],
body.dark-mode .buddypress .buddypress-wrap button.pending, body.dark-mode .buddypress .buddypress-wrap button.disabled, body.dark-mode .buddypress .buddypress-wrap div.pending a, body.dark-mode .buddypress .buddypress-wrap a.disabled,
body.dark-mode .buddypress .buddypress-wrap button.text-button, body.dark-mode .buddypress .buddypress-wrap input.text-button, body.dark-mode .buddypress .buddypress-wrap .text-links-list a.button, body.dark-mode .buddypress-wrap .bp-messages p,
body.dark-mode .widget.buddypress .item-options a, body.dark-mode .rtmedia-media-description, body.dark-mode .sidebar .rtmedia-no-media-found, body.dark-mode .doctable tbody .row-actions, body.dark-mode .shortcode-login-desc, body.dark-mode .shortcode-login .status, body.dark-mode .shortcode-login .forgetmenot label,
body.dark-mode .shortcode-login-bottom a, body.dark-mode .shordcode-recent-comment .recent-comment-info, body.dark-mode .sidebar .shordcode-recent-comment .recent-comment-info a, body.dark-mode .shortcode-bp-groups-tabs-container .group-box-details,
body.dark-mode .shortcode-bp-groups-container .group-box-details, body.dark-mode #groups-list .group-box-details, body.dark-mode .shortcode-small-recent-posts-container .recent-post-bottom, body.dark-mode .sidebar .shortcode-small-recent-posts-container .recent-post-bottom a,
body.dark-mode .shortcode-popular-posts .shortcode-popular-posts-menu-drop-down, body.dark-mode .shortcode-popular-posts .shortcode-popular-posts-likes, body.dark-mode #sidenav ul#sidenav-ul .sidenav-member-activity, body.dark-mode #sidenav-members #sidenav-members-nav li,
body.dark-mode #sidenav-members.sidenav-expand .sidenav-leaderboard-row .leaderboard-points, body.dark-mode #tabs-activity .tabs-activity-nav li, body.dark-mode .shortcode-activity a.activity-time-since, body.dark-mode .shortcode-event-location,
body.dark-mode #shortcode-category-posts .shortcode-category-posts-menu li a, body.dark-mode #shortcode-category-posts .cat-posts-list .recent-post-bottom, body.dark-mode .big-leaderboard-row .leaderboard-position,
body.dark-mode .small-leaderboard-row .leaderboard-points,
body.dark-mode #bbpress-forums div.bbp-forum-author .bbp-author-role, body.dark-mode #bbpress-forums div.bbp-topic-author .bbp-author-role, body.dark-mode #bbpress-forums div.bbp-reply-author .bbp-author-role, body.dark-mode span.bbp-author-ip, body.dark-mode div.bbp-breadcrumb, body.dark-mode div.bbp-breadcrumb p, body.dark-mode #bbpress-forums div.bbp-breadcrumb p a,
body.dark-mode span.bbp-admin-links, body.dark-mode span.bbp-admin-links a, body.dark-mode #bbpress-forums p.bbp-topic-meta a, body.dark-mode div.bbp-template-notice a:hover, body.dark-mode #bbpress-forums .bbp-topic-content ul.bbp-topic-revision-log, body.dark-mode #bbpress-forums .bbp-reply-content ul.bbp-topic-revision-log, body.dark-mode #bbpress-forums .bbp-reply-content ul.bbp-reply-revision-log,
body.dark-mode .bbp-forum-freshness, body.dark-mode .bbp-forum-freshness a, body.dark-mode.woocommerce .comment-text p.meta, body.dark-mode.woocommerce .comment-text p.meta a, body.dark-mode.woocommerce .comment-text p.meta strong,
body.dark-mode #shortcode-category-posts .box-blog-likes, body.dark-mode #shortcode-category-posts .box-blog-comments, body.dark-mode .shortcode-activity-meta .comments-count, body.dark-mode .wpulike .count-box, body.dark-mode #buddypress .activity-content .activity-meta .wpulike-heart .count-box,
body.dark-mode .single-post-details .single-blog-comments, body.dark-mode .single-post-details .wpulike-heart .count-box, body.dark-mode .box-blog-entry .box-blog-comments, body.dark-mode .box-blog-entry .box-blog-likes,
body.dark-mode ul.forum-lastposts-container .forum-lastposts-details, body.dark-mode .sidebar ul.forum-lastposts-container .forum-lastposts-details a, body.dark-mode .shortcode-popular-posts-time, body.dark-mode .item-list .activity, body.dark-mode #bp-data-export button { color: <?php echo get_theme_mod( 'onecommunity_dark_mode_font_color_darker', '#848484' ); ?>!important; }
body.dark-mode div#dark-mode-container #dark-mode svg, body.dark-mode #buddypress div.activity-meta .count-box, body.dark-mode #buddypress .acomment-options .count-box { fill:<?php echo get_theme_mod( 'onecommunity_dark_mode_font_color_darker', '#848484' ); ?>; }


body.dark-mode #object-nav .tabs-nav li.current, body.dark-mode #buddypress .main-navs.users-nav.main-navs.bp-navs ul li.current a, body.dark-mode #buddypress .main-navs.groups-nav.main-navs.bp-navs ul li.current a, body.dark-mode .generic-button, body.dark-mode #object-nav ul li.current a, body.dark-mode .single-post-category a, body.dark-mode #object-nav ul li.current, body.dark-mode .front-info-box h1, body.dark-mode .front-info-box h1 a, body.dark-mode .shortcode_go a, body.dark-mode .elementor-button-text, body.dark-mode .elementor .elementor-container .elementor-widget-button a.elementor-button-link .elementor-button-text, body.dark-mode .elementor .elementor-container .elementor-widget-button a.elementor-button-link { color:#ffffff!important; }

body.dark-mode .frontpage-row-1 { background: <?php echo get_theme_mod( 'onecommunity_dark_mode_background_1_row', '#252122' ); ?>!important; }

<?php } ?>

</style>
<?php
}
add_action('wp_head', 'onecommunity_enqueue_customizer_style');
add_action('login_enqueue_scripts', 'onecommunity_enqueue_customizer_style');
